### ISSUE TITLE
Cti.EVENT.RINGING only fires for direct calls (and not for ring group calls)

### ISSUE THREAD

**Issue by MischaSz** [VoIPstudio/cti-connector#1]
Hi!

We're trying to implement cti-connector to signal incoming calls on our company dashboard (LCD screen). We have so far successfully implemented the basic code - however, the corresponding event handler only gets fired for direct calls to the user's number. Incoming calls for a ring group (eg. our main number) where the user is member are not signaled. Is there a way how we can fire the event handler for calls on the ring group (where the user is member of)?

Regards Mischa

**Comment by kadryjanek** [comment]
Hi Mischa,

Thank you for your ticket. You are right: for now you will receive events only for `direct` calls. 

I you need `hotfix` please comment lines: https://github.com/level7systems/cti-connector/blob/master/cti-connector.js#L553-L555
Official release will be ready soon. 

Regards,
Kamil

**Comment by kadryjanek** [comment]
This has been resolved in latest release: [v1.0.4](https://github.com/level7systems/cti-connector/releases/tag/v1.0.4).
